### ISSUE TITLE
future compatibility problem in dependencies

### ISSUE THREAD

**Issue by hdhoang** [hadrien-psydk/dkalc#1]
Hi, due to rust-lang/rust#49799, one of your dependencies will no longer build. From looking at your Cargo.toml, we recommend you upgrade to
 a newer gtk-rs. Thanks for your attention!

**Comment by hadrien-psydk** [comment]
Thank you for the notification. I have been able to upgrade to gtk-rs 0.3.0 but unfortunately using 0.4.0 gets me this error:
```
no method named `print_system_libs` found for type `pkg_config::Config` in the current scope
```

**Comment by hadrien-psydk** [comment]
I deleted Cargo.lock and it was rebuilt with the correct dependencies this time. dkalc now uses gtk-rs 0.4
